# This is a basic workflow to help you get started with Actions

name: RustAudit

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
      
  test:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --no-fail-fast >> test_result.txt
      - uses: actions/upload-artifact@v1
        with:
          name: test-results-report
          path: test_result.txt

  clippy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  audit:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - name: rust-audit-check
        uses: actions-rs/audit-check@v1.2.0
        with:
          # GitHub Actions token
          token: ${{ secrets.GITHUB_TOKEN }}
          
  tarpaulin:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/tarpaulin@v0.1
        with:
          out-type: "Html"
      - uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: tarpaulin-report.html
