# This is a basic workflow to help you get started with Actions

name: RustAudit

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
      
  test:
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      output1: ${{ steps.build_step.outputs }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - id: build_step
        run: cargo test --no-fail-fast >> $GITHUB_OUTPUT

      
  test-output:
    runs-on: ubuntu-latest
    name: Test Report
    needs: [test]
    steps:
      - run: |
          echo "#Test report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "${{needs.test.outputs.output1}}" >> $GITHUB_STEP_SUMMARY
      
  clippy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  audit:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - name: rust-audit-check
        uses: actions-rs/audit-check@v1.2.0
        with:
          # GitHub Actions token
          token: ${{ secrets.GITHUB_TOKEN }}
